# Generated by Django 5.2.13 on 2026-04-22 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentWeiboInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.CharField(max_length=255, unique=True, verbose_name='wb_id')),
                ('wb_userId', models.CharField(default='', max_length=255, verbose_name='用户ID')),
                ('wb_userName', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('wb_user_profile_image_url', models.URLField(default='', verbose_name='用户头像')),
                ('wb_text', models.TextField(default='', verbose_name='微博内容')),
                ('wb_created_at', models.DateTimeField(blank=True, null=True, verbose_name='微博发布时间')),
                ('wb_source', models.CharField(default='', max_length=255, verbose_name='来源')),
                ('wb_pic_ids', models.JSONField(blank=True, default=list, null=True, verbose_name='图片ID列表')),
                ('wb_like_num', models.CharField(default='', max_length=255, verbose_name='微博点赞数')),
                ('wb_comment_num', models.CharField(default='', max_length=255, verbose_name='微博评论数')),
                ('wb_repost_num', models.CharField(default='', max_length=255, verbose_name='微博转发数')),
            ],
            options={
                'verbose_name': '微博评论信息',
                'verbose_name_plural': '微博评论信息',
                'db_table': 'SpiderAPI_CommentWeiboInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=255, verbose_name='uid')),
                ('cookie', models.CharField(default='', max_length=2048, verbose_name='cookie')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='add_time')),
            ],
            options={
                'verbose_name': '爬取目标',
                'verbose_name_plural': '爬取目标',
                'db_table': 'SpiderAPI_target',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Image', models.CharField(max_length=255, verbose_name='头像地址')),
                ('NickName', models.CharField(max_length=255, verbose_name='昵称')),
                ('Gender', models.CharField(default='', max_length=10, verbose_name='性别')),
                ('Province', models.CharField(default='', max_length=100, verbose_name='省份')),
                ('City', models.CharField(default='', max_length=100, verbose_name='城市')),
                ('Birthday', models.CharField(default='', max_length=50, verbose_name='生日')),
                ('Constellation', models.CharField(default='', max_length=50, verbose_name='星座')),
                ('Location', models.CharField(default='', max_length=255, verbose_name='所在地')),
                ('URL', models.URLField(default='', max_length=255, verbose_name='首页链接')),
                ('Num_Follows', models.CharField(default='', max_length=255, verbose_name='关注数')),
                ('Num_Fans', models.CharField(default='', max_length=255, verbose_name='粉丝数')),
                ('Num_Tweets', models.CharField(default='', max_length=255, verbose_name='微博数')),
                ('Education', models.CharField(default='', max_length=255, verbose_name='教育信息')),
                ('Company', models.CharField(default='', max_length=255, verbose_name='公司信息')),
                ('Tags', models.CharField(default='', max_length=255, verbose_name='标签')),
                ('Description', models.CharField(default='', max_length=255, verbose_name='简介')),
                ('BriefIntroduction', models.CharField(default='', max_length=500, verbose_name='简价')),
                ('SexOrientation', models.CharField(default='', max_length=50, verbose_name='性取向')),
                ('Sentiment', models.CharField(default='', max_length=50, verbose_name='感情状况')),
                ('VIPlevel', models.CharField(default='', max_length=50, verbose_name='会员等级')),
                ('Verified', models.BooleanField(default=False, verbose_name='是否认证')),
                ('Verified_reason', models.CharField(default='', max_length=255, verbose_name='认证原因')),
                ('verified_type', models.CharField(default='', max_length=10, verbose_name='认证类型')),
                ('follow_me', models.BooleanField(default=False, verbose_name='是否关注我')),
                ('following', models.BooleanField(default=False, verbose_name='是否正在关注')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'SpiderAPI_UserInfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('c_userId', models.CharField(default='', max_length=255, verbose_name='用户ID')),
                ('c_userName', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('c_user_profile_image_url', models.URLField(default='', verbose_name='用户头像')),
                ('c_user_profile_url', models.URLField(default='', verbose_name='用户首页')),
                ('c_source', models.CharField(default='', max_length=255, verbose_name='来源')),
                ('c_text', models.TextField(default='', verbose_name='评论内容')),
                ('c_created_at', models.DateTimeField(blank=True, null=True, verbose_name='评论时间')),
                ('c_like_num', models.CharField(default='', max_length=255, verbose_name='点赞数')),
                ('c_sentiments', models.CharField(default='', max_length=50, verbose_name='情感分析')),
                ('CommentWeiboInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='SpiderAPI.commentweiboinfo')),
            ],
            options={
                'verbose_name': '评论详情',
                'verbose_name_plural': '评论详情',
                'db_table': 'SpiderAPI_CommentInfo',
                'ordering': ['-c_like_num'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TweetsInfo',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField(default='', verbose_name='微博内容')),
                ('PubTime', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('PubTools', models.CharField(default='', max_length=255, verbose_name='发布工具')),
                ('Like', models.CharField(default='', max_length=255, verbose_name='点赞数')),
                ('Comment', models.CharField(default='', max_length=255, verbose_name='评论数')),
                ('Transfer', models.CharField(default='', max_length=255, verbose_name='转发数')),
                ('Image', models.TextField(default='', verbose_name='图片地址')),
                ('tags', models.CharField(default='', max_length=255, verbose_name='标签')),
                ('pinyin', models.CharField(default='', max_length=1024, verbose_name='拼音')),
                ('sentiments', models.CharField(default='', max_length=50, verbose_name='情感分析')),
                ('UserInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='SpiderAPI.userinfo')),
            ],
            options={
                'verbose_name': '微博信息',
                'verbose_name_plural': '微博信息',
                'db_table': 'SpiderAPI_TweetsInfo',
                'ordering': ['-PubTime'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImgInfo',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wordcloud', models.JSONField(default=dict, verbose_name='词云数据')),
                ('UserInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='img_info', to='SpiderAPI.userinfo')),
            ],
            options={
                'verbose_name': '图片信息',
                'verbose_name_plural': '图片信息',
                'db_table': 'SpiderAPI_ImgInfo',
                'managed': True,
            },
        ),
    ]
