# Generated by Django 5.2.13 on 2026-04-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinfo',
            name='c_created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='c_userId',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='c_userName',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='commentweiboinfo',
            name='wb_created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='微博发布时间'),
        ),
        migrations.AlterField(
            model_name='commentweiboinfo',
            name='wb_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='wb_id'),
        ),
        migrations.AlterField(
            model_name='commentweiboinfo',
            name='wb_userId',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='commentweiboinfo',
            name='wb_userName',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='target',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='target',
            name='uid',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True, verbose_name='uid'),
        ),
        migrations.AlterField(
            model_name='tweetsinfo',
            name='PubTime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='NickName',
            field=models.CharField(db_index=True, max_length=255, verbose_name='昵称'),
        ),
    ]
