# Generated by Django 5.2.13 on 2026-04-23 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0002_alter_commentinfo_c_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinfo',
            name='CommentWeiboInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='SpiderAPI.commentweiboinfo', to_field='wb_id'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='c_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='评论ID'),
        ),
        migrations.AlterField(
            model_name='commentinfo',
            name='c_like_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='commentweiboinfo',
            name='wb_comment_num',
            field=models.IntegerField(default=0, verbose_name='微博评论数'),
        ),
        migrations.AlterField(
            model_name='commentweiboinfo',
            name='wb_like_num',
            field=models.IntegerField(default=0, verbose_name='微博点赞数'),
        ),
        migrations.AlterField(
            model_name='commentweiboinfo',
            name='wb_repost_num',
            field=models.IntegerField(default=0, verbose_name='微博转发数'),
        ),
        migrations.AlterField(
            model_name='tweetsinfo',
            name='Comment',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='tweetsinfo',
            name='Like',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='tweetsinfo',
            name='Transfer',
            field=models.IntegerField(default=0, verbose_name='转发数'),
        ),
        migrations.AlterField(
            model_name='tweetsinfo',
            name='_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='微博ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Num_Fans',
            field=models.IntegerField(default=0, verbose_name='粉丝数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Num_Follows',
            field=models.IntegerField(default=0, verbose_name='关注数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Num_Tweets',
            field=models.IntegerField(default=0, verbose_name='微博数'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='搜索关键词')),
                ('weibo_id', models.CharField(default='', max_length=50, verbose_name='微博ID')),
                ('nickname', models.CharField(default='', max_length=255, verbose_name='用户昵称')),
                ('search_time', models.DateTimeField(auto_now_add=True, verbose_name='搜索时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '搜索记录',
                'verbose_name_plural': '搜索记录',
                'db_table': 'SpiderAPI_SearchHistory',
                'ordering': ['-search_time'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'SpiderAPI_UserProfile',
                'managed': True,
            },
        ),
    ]
