# Generated by Django 5.2.13 on 2026-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0003_alter_commentinfo_commentweiboinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipsInfo',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='关系ID')),
                ('fan_id', models.CharField(db_index=True, max_length=50, verbose_name='关注者ID')),
                ('followed_id', models.CharField(db_index=True, max_length=50, verbose_name='被关注者ID')),
                ('crawl_time', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
            ],
            options={
                'verbose_name': '用户关系',
                'verbose_name_plural': '用户关系',
                'db_table': 'SpiderAPI_RelationshipsInfo',
                'managed': True,
            },
        ),
    ]
