# Generated by Django 5.2.13 on 2026-05-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderAPI', '0004_relationshipsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='group',
            field=models.IntegerField(default=0, verbose_name='用户分组'),
        ),
        migrations.AddField(
            model_name='target',
            name='isScrapy',
            field=models.IntegerField(default=0, verbose_name='是否已爬取'),
        ),
    ]
